### ISSUE TITLE
Error with gunicorn when running kong/httpbin:0.2.0

### ISSUE THREAD

**Issue by sofia-fernandez-six** [Kong/httpbin#62]
Hi,

The latest release of httpbin broke the image. When I now try to start running it I get the following error:

`gunicorn": executable file not found in $PATH: unknown
`

Comparing with version 0.1.0 I noticed that gunicorn is not in `/usr/local/bin` anymore
![image](https://github.com/user-attachments/assets/7b9a63e6-afb2-46f0-8910-330427e8f2c2)

**Comment by VBranimir** [comment]
Added a new PR that should fix this: 

https://github.com/Kong/httpbin/pull/63

**Comment by sofia-fernandez-six** [comment]
maybe a contributor can take a look?
@pmalek last time, he released my issue #59

**Comment by pmalek** [comment]
It's already available under: https://hub.docker.com/r/kong/httpbin/tags

https://hub.docker.com/layers/kong/httpbin/0.2.1/images/sha256-6b7621377c31d1b3b817b37267012f940902d7a7fea7f6002c037eed00979bc2?context=explore

**Comment by sofia-fernandez-six** [comment]
For me, i'm facing the same issue @pmalek 
```
Error: container create failed: time="2024-10-28T10:56:04Z" level=error msg="runc create failed: unable to start container process: exec: \"gunicorn\": executable file not found in $PATH"
```
This is my deployment in Openshift:
```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: httpbin
  labels:
    app: httpbin
    helm.sh/chart: apip-httpbin-1.0.4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: httpbin
    spec:
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources:
            limits:
              cpu: '1'
              memory: 256Mi
            requests:
              cpu: 5m
              memory: 60Mi
          readinessProbe:
            httpGet:
              path: /get
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: httpbin
          command:
            - gunicorn
            - '-b'
            - '0.0.0.0:9090'
            - 'httpbin:app'
            - '-k'
            - gevent
            - '-t'
            - '0'
          livenessProbe:
            httpGet:
              path: /get
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          image: 'kong/httpbin:0.2.1'
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
```
